use_frameworks!

platform :ios, '10.0'

target 'YDPreventCrash_Example' do
  pod 'YDPreventCrash', :path => '../'

  target 'YDPreventCrash_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
